### ISSUE TITLE
Publish more

### ISSUE THREAD

**Issue by funny-falcon** [claygod/Bxog#1]
Почему только на хабре?
Послушай коммент с хабра: все сущности, которые не нужны пользователю, сделай приватными.
И публикуй в golang-nuts гугл группе, а также в golang сабреддите (reddit.com/r/golang)

**Comment by claygod** [comment]
По первому не спорю, всё верно. По второму - боюсь, мой английский оставляет желать лучшего. Т.е. статью я перевести не смогу, ну, чтобы не "моя-твоя не понимай" ('nj ghj golang-nuts).
На reddit опубликовал:
https://www.reddit.com/r/golang/comments/4kmjnx/bxog_is_a_new_simple_and_fast_http_router_for_go/

Спасибо за подсказки, т.к. я ещё новичок в Go сообществе.

**Comment by funny-falcon** [comment]
Статью переводить не надо. Просто анонс сделай.
И друзей не стесняйся просить переводить. Наверняка же рядом есть кто-то, кто знает английский лучше.
Я часто прибегаю к услугам http://www.lingvo-online.ru/ru и иногда https://translate.google.com/ .

**Comment by claygod** [comment]
Сделал анонс:

https://groups.google.com/forum/#!topic/golang-nuts/QebjZnA-TvU
