### ISSUE TITLE
I think, I found an error in the example

### ISSUE THREAD

**Issue by eremenkomax** [claygod/Bxog#4]
Hello.

Thank you for this framework! 

When I start your example, I saw an error in the output. If I used a recommended url  http://localhost/country/USA/capital/Washington/valuta/dollar, I did't see a Country in the last string and I saw "Moscow" in the capital place.

I think, the code below is more right (and I replaced "valuta" to "currency"):

package main

import (
	"io"
	"net/http"

	"github.com/claygod/bxog"
)

// Handlers
func IHandler(w http.ResponseWriter, req *http.Request, r *bxog.Router) {
	io.WriteString(w, "Welcome to Bxog!")
}
func THandler(w http.ResponseWriter, req *http.Request, r *bxog.Router) {
	params := r.Params(req, "/abc/:para")
	io.WriteString(w, "Params:\n")
	io.WriteString(w, " 'par' -> "+params["par"]+"\n")
}
func PHandler(w http.ResponseWriter, req *http.Request, r *bxog.Router) {
	// Getting parameters from URL
	params := r.Params(req, "country")
	io.WriteString(w, "Country:\n")
	io.WriteString(w, " 'Name' -> "+params["name"]+"\n")
	io.WriteString(w, " 'Capital' -> "+params["city"]+"\n")
	io.WriteString(w, " 'Currency' -> "+params["money"]+"\n")
	// Creating a URL string
	io.WriteString(w, "Creating a URL from route:\n")
	io.WriteString(w, r.Create("country", params))

}

// Main
func main() {
	m := bxog.New()
	m.Add("/", IHandler)
	m.Add("/abc/:par", THandler)
	m.Add("/country/:name/capital/:city/currency/:money", PHandler).
		Id("country"). // For ease indicate the short ID
		Method("GET")  // GET method do not need to write here, it is used by default (this is an example)
	m.Start(":80")
}

**Comment by claygod** [comment]
Hello!

This example demonstrates just **two** options:
1) to obtain the parameters from the command line
2) Create a new URL with the help of 55

In the first case we get the parameters and display them on the screen, and in the second we decided to make a new URL. This is just a demonstration of what the new URL can be created not by hand, and with the help of a router. (This is done for the convenience!)

Summary: _This is not a bug, it's a feature_
